{%- from "kubernetes/map.jinja" import common with context -%}
apiVersion: v1
kind: Endpoints
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
    addonmanager.kubernetes.io/mode: Reconcile
subsets:
  - addresses:
    - ip: {{ common.addons.heapster_influxdb.public_ip }}

    ports:
    - port: 8082
      protocol: TCP
